### PR TITLE
Create search api and pass search results to view

### PR DESCRIPTION
**Pull request by zamiang**

### CODE REVIEW

**Comment by zamiang** [comment]
@builtbylane very basic search results and user items pages are in here

screenshot 2016-11-18 23 49 56

**Comment by zamiang** [comment]
screenshot 2016-11-19 15 55 31
screenshot 2016-11-19 15 55 03

@builtbylane this should be good to review. let me know what is up next!

**Comment by builtbylane** [comment]
@zamiang  can you make .js-project-title an input text field to allow users to re-search from the search page. Also, on the homepage. can you hook up that search input.

**Comment by zamiang** [comment]
Yea I'll make the title of the search page an input. 

Can you give me a bit more detail about how the search input should work on the homepage? Right now it is an input that directs to /search/{{ query }} on enter. Is that not what it should do?

**Pull request merged**
